# Generated by Django 3.2.4 on 2021-06-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numReview',
            new_name='numReviews',
        ),
    ]
